base/urls.py
from django.urls import path
from . import views
from .views import BoxUpdate, Boxes, BoxDetail, BoxCreate, BoxUpdate, CustomLoginView, RegisterPage, BoxUpload
from django.contrib.auth.views import LogoutView
from django.conf import settings
from django.views.generic import TemplateView

urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login'),
    path('register/', RegisterPage.as_view(), name='register'),
    path('logout/', LogoutView.as_view(next_page='login'), name='logout'),
    path('', Boxes.as_view(), name="boxes"),
    path('box/<int:pk>', BoxDetail.as_view(), name="box-detail"),
    path('create-box/', BoxCreate.as_view(), name="box-create"),
    path('update-box/<int:pk>', BoxUpdate.as_view(), name="box-update"),
    path('upload/', BoxUpload.as_view(), name="box-upload"),
]

#urlpatterns += static(settings.NMAP_URL, document_root=settings.NMAP_ROOT)

jvis/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls'))
]

base/models.py
from django.db import models
from django.db.models.fields import IPAddressField
from django.contrib.auth.models import User
from django.contrib.auth.models import Group
from django.forms.models import ModelForm
from base.modules.notifications import Notification


class Box(models.Model):

    __original_ip = None
    __original_hostname = None
    __original_state = None

    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    ip = models.GenericIPAddressField(null=False,blank=False)
    hostname = models.CharField(max_length=200, null=True, blank=True)
    state = models.CharField(max_length=200, null=True, blank=True)
    comments = models.TextField(null=True, blank=True)
    active = models.BooleanField(default=False)
    pwned = models.BooleanField(default=False)
    unrelated = models.BooleanField(default=False)
    comeback = models.BooleanField("Come back to this box", default=False)
    os = models.CharField(max_length=200, null=True, blank=True)
    new = models.BooleanField(default=True)
    updated = models.BooleanField(default=False)
    cidr = models.CharField(max_length=200, default="/24",null=True, blank=True)
    orderedip = models.BigIntegerField(null=True, blank=True, default=0)

    @property
    def get_ordered_ip(self):
        octets = self.ip.split(".")
        octet_num = (int(octets[0]) * 256^3) +  (int(octets[1]) * 256^2) + (int(octets[2]) * 256) + int(octets[3])
        return octet_num


    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.__original_ip = self.ip
        self.__original_hostname = self.hostname
        self.__original_state = self.state


    def save(self, force_insert=False, force_update=False, *args, **kwargs):
        if (self.hostname != self.__original_hostname) or (self.state != self.__original_state):
            self.updated = True
        self.orderedip = self.get_ordered_ip
        self.__original_ip = self.ip
        self.__original_hostname = self.hostname
        self.__original_state = self.state
        super().save(force_insert, force_update, *args, **kwargs)



    def __str__(self):
        return self.ip

    class Meta:
        ordering = ['orderedip']

class BoxService(models.Model):

    __original_port = None
    __original_protocol = None
    __original_state = None
    __original_name = None
    __original_version = None
    __original_script = None
    
    port = models.IntegerField(blank=True)
    protocol = models.CharField(max_length=200, blank=True)
    state = models.TextField(null=True, blank=True)
    name = models.TextField(null=True, blank=True)
    version = models.TextField(null=True, blank=True)
    script = models.TextField(null=True,blank=True)
    new = models.BooleanField(default=True)
    updated = models.TextField(default=None,null=True, blank=True)
    #updated = models.BooleanField(default=False)
    cBox = models.ForeignKey(Box, on_delete=models.CASCADE)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.__original_port = self.port
        self.__original_protocol = self.protocol
        self.__original_state = self.state
        self.__original_name = self.name
        self.__original_version = self.version
        self.__original_script = self.script

    def save(self, force_insert=False, force_update=False, *args, **kwargs):
        temp = ""
        if self.protocol != self.__original_protocol:
            #n.append_notification(self.cBox, self.port, True, None, {"protocol":self.protocol})
            temp += "protocol: {}\n".format(self.protocol)
        if self.state != self.__original_state:
            temp += "state: {}\n".format(self.state)
        if self.name != self.__original_name:
            temp += "name: {}\n".format(self.name)
        if  self.version != self.__original_version:
            temp += "version: {}\n".format(self.version)
        if  self.script != self.__original_script:
            temp += "script: {}\n".format(self.script)
        if temp:
            self.updated = temp


        super().save(force_insert, force_update, *args, **kwargs)
        self.__original_port = self.port
        self.__original_protocol = self.protocol
        self.__original_state = self.state
        self.__original_name = self.name
        self.__original_version = self.version
        self.__original_script = self.script

    def __str__ (self):
        return str(self.port)

    class Meta:
        ordering=['port']

base/forms.py
from django import forms

class UploadFileForm(forms.Form):
    file = forms.FileField()
    

base/views.py
from base.models import Box
from django.shortcuts import render, redirect
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, FormView
from django.views import View
from django.db.models import Q
from django.urls import reverse_lazy
import asyncio
import json
import os
import functools
import operator
from django.contrib.auth.views import LoginView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import UserCreationForm
from django.http import HttpResponseRedirect
from django.contrib.auth import login
from django import http
from base.modules.create_box import handle_uploaded_box
from base.modules import diagram
from .models import Box, BoxService
from .forms import UploadFileForm 
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import classonlymethod, method_decorator
from django.http.response import JsonResponse, HttpResponse
from django.views.decorators.http import require_GET, require_POST
from django.shortcuts import get_object_or_404
from django.contrib.auth.models import User
from django.conf import settings

#pip install --upgrade pip
#install nmap
#install unzip, wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip unzip ngrok-stable-linux-amd64.zip
class CustomLoginView(LoginView):
    template_name = 'base/login.html'
    fields = '__all__'
    redirect_authenticated_user = True

    def get_success_url(self):
        return reverse_lazy('boxes')

class RegisterPage(FormView):
    template_name = 'base/register.html'
    form_class = UserCreationForm
    redirect_authenticated_user = True
    success_url = reverse_lazy('boxes')

    def form_valid(self, form):
        user = form.save()
        if user is not None:
            login(self.request, user)
        return super(RegisterPage, self).form_valid(form)
    
    def get(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            return redirect('boxes')
        return super(RegisterPage, self).get(*args, **kwargs)


class Boxes(LoginRequiredMixin, ListView):
    model = Box
    context_object_name = 'boxes'


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['chk'] = ""
        search_input = self.request.GET.get('search') or ''
        if search_input:
            if 'port=' in search_input:
                port_string=search_input.split("port=",1)[1]
                ports=port_string.split(",")
                if self.request.GET.get('exactmatch'):
                    context['chk'] = "checked"
                    and_filter = "context['boxes'] = Box.objects"
                    for port in ports:
                        port = int(port.strip())
                        and_filter += ".filter(boxservice__port={})".format(port)
                    exec(and_filter)
                else:
                    context['chk'] = ""
                    for port in ports:
                        port = int(port.strip())       
                    port_search = (Q(boxservice__port=po) for po in ports)
                    context['boxes'] = Box.objects.filter(functools.reduce(operator.or_, port_search)).distinct()
            elif 'script=' in search_input:
                script_string=search_input.split("script=",1)[1]
                context['boxes'] = Box.objects.filter(boxservice__script__icontains=script_string).distinct()
                if self.request.GET.get('exactmatch'):
                    context['chk'] = "checked"
                else:
                    context['chk'] = ""
            elif 'version=' in search_input:
                version_string=search_input.split("version=",1)[1]
                if self.request.GET.get('exactmatch'):
                    context['chk'] = "checked"
                    context['boxes'] = Box.objects.filter(boxservice__version__iexact=version_string).distinct()
                else:
                    context['chk'] = ""
                    context['boxes'] = Box.objects.filter(boxservice__version__icontains=version_string).distinct()
            elif 'name=' in search_input:
                name_string = search_input.split("name=",1)[1]
                if self.request.GET.get('exactmatch'):
                    context['chk'] = "checked"
                    context['boxes'] = Box.objects.filter(boxservice__name__iexact=name_string).distinct()
                else:
                    context['chk'] = ""
                    context['boxes'] = Box.objects.filter(boxservice__name__icontains=name_string).distinct()
            elif 'user=' in search_input:
                user_string = search_input.split("user=",1)[1]
                if self.request.GET.get('exactmatch'):
                    context['chk'] = "checked"
                    context['boxes'] = Box.objects.filter(user__username__iexact=user_string).distinct()
                else:
                    context['chk'] = ""
                    context['boxes'] = Box.objects.filter(user__username__icontains=user_string).distinct()
            else:
                if self.request.GET.get('exactmatch'):
                    context['chk'] = "checked"
                    context['boxes'] = context['boxes'].filter(Q(ip__iexact=search_input) | Q(hostname__iexact=search_input)).distinct()
                else:
                    context['chk'] = ""
                    context['boxes'] = context['boxes'].filter(Q(ip__icontains=search_input) | Q(hostname__icontains=search_input)).distinct()
            context['search_input'] = search_input
        context['count'] = context['boxes'].count()
        return context

    def post(self, request, *args, **kwargs):
        context_boxes = None
        if 'run_diagram' in request.POST:
            return diagram.create_diagram()
        elif 'run_topology' in request.POST:
            return diagram.create_topology()
        elif 'run_hostlist' in request.POST:
            search_input = self.request.GET.get('search') or ''
            if search_input:
                if 'port=' in search_input:

                    port_string=search_input.split("port=",1)[1]
                    ports=port_string.split(",")
                    if self.request.GET.get('exactmatch'):
                        and_filter = "context_boxes = Box.objects"
                        for port in ports:
                            port = int(port.strip())
                            and_filter += ".filter(boxservice__port={})".format(port)
                        ldic = locals()
                        exec(and_filter, globals(), ldic)
                        context_boxes = ldic["context_boxes"]
                    else:
                        for port in ports:
                            port = int(port.strip())       
                        port_search = (Q(boxservice__port=po) for po in ports)
                        context_boxes= Box.objects.filter(functools.reduce(operator.or_, port_search)).distinct()
                elif 'script=' in search_input:
                    script_string=search_input.split("script=",1)[1]
                    context_boxes = Box.objects.filter(boxservice__script__icontains=script_string).distinct()
                elif 'version=' in search_input:
                    version_string=search_input.split("version=",1)[1]
                    if self.request.GET.get('exactmatch'):
                        context_boxes = Box.objects.filter(boxservice__version__iexact=version_string).distinct()
                    else:
                        context_boxes = Box.objects.filter(boxservice__version__icontains=version_string).distinct()
                elif 'name=' in search_input:
                    name_string = search_input.split("name=",1)[1]
                    if self.request.GET.get('exactmatch'):
                        context_boxes = Box.objects.filter(boxservice__name__iexact=name_string).distinct()
                    else:
                        context_boxes = Box.objects.filter(boxservice__name__icontains=name_string).distinct()
                elif 'user=' in search_input:
                    user_string = search_input.split("user=",1)[1]
                    if self.request.GET.get('exactmatch'):
                        context_boxes = Box.objects.filter(user__username__iexact=user_string).distinct()
                    else:
                        context_boxes = Box.objects.filter(user__username__icontains=user_string).distinct()
                else:
                    if self.request.GET.get('exactmatch'):
                        context_boxes = Box.objects.filter(Q(ip__iexact=search_input) | Q(hostname__iexact=search_input)).distinct()
                    else:
                        context_boxes = Box.objects.filter(Q(ip__icontains=search_input) | Q(hostname__icontains=search_input)).distinct()
            else:
                context_boxes = Box.objects.all()
            return diagram.create_hostlist(context_boxes)
class BoxDetail(LoginRequiredMixin, DetailView):
    model = Box
    context_object_name = 'box'
    template_name='base/box.html'

class BoxCreate(LoginRequiredMixin, CreateView):
    model = Box
    context_object_name = 'box_form'
    fields = ['user', 'comments', 'active']
    success_url = reverse_lazy('boxes')

class BoxUpdate(LoginRequiredMixin, UpdateView):
    model = Box
    fields = ['user', 'hostname', 'os', 'cidr', 'comments', 'active', 'pwned','comeback','unrelated']
    context_object_name='box_form'
    success_url = reverse_lazy('boxes')
    context_object_name = 'boxes'


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['ip'] = context['boxes'].ip
        return context


@method_decorator(csrf_exempt, name="dispatch")
class BoxUpload(View):
    def post(self, request, *args, **kwargs):

base/templates/base/box.html
{% extends 'base/main.html' %}
{% block content %}
<a href="{% url 'boxes' %}">Go Back</a>
<h1>Box: {{box}}</h1>
<h1>Host Name: {{box.hostname}}</h1>
<h2>OS: {{box.os}}</h2>
<h2>Services:</h2>
<table>
    <thead>
        <tr>
            <th>Port</th>
            <th>Protocol</th>
            <th>State</th>
            <th>Name</th>
            <th>Version</th>
        </tr>
    </thead>
    <tbody>
    {% for b in box.boxservice_set.all %}
        <tr>
            <td>{{b.port}}</td>
            <td>{{b.protocol}}</td>
            <td>{{b.state}}</td>
            <td>{{b.name}}</td>
            <td>{{b.version}}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>
<p>Active: {{box.active}}</p>
<p>Comments: {{box.comments}}</p>
{% endblock content %}

base/templates/base/box_form.html
{% extends 'base/main.html' %}
{% block content %}

<style>
#formContent {
  -webkit-border-radius: 10px 10px 10px 10px;
  border-radius: 10px 10px 10px 10px;
  background: #fff;
  padding: 30px;
  width: 90%;
  max-width: 650px;
  position: relative;
  padding: 30px;
  -webkit-box-shadow: 0 2px 5px 0 rgba(0,0,0,0.3);
  box-shadow: 0 2px 5px 0 rgba(0,0,0,0.3);
  text-align: center;
}

.wrapper {
  display: flex;
  align-items: center;
  flex-direction: column; 
  justify-content: center;
  width: 100%;
  min-height: 100%;
  padding: 20px;
}

input[type=button], input[type=submit], input[type=reset]  {
  background-color: #56baed;
  border: none;
  color: white;
  width: 85%;
  padding: 10px 25px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  text-transform: uppercase;
  font-size: 16px;
  cursor: pointer;
  -webkit-border-radius: 5px 5px 5px 5px;
  border-radius: 5px 5px 5px 5px;
  margin: 5px 20px 40px 20px;
  -webkit-transition: all 0.3s ease-in-out;
  -moz-transition: all 0.3s ease-in-out;
  -ms-transition: all 0.3s ease-in-out;
  -o-transition: all 0.3s ease-in-out;
  transition: all 0.3s ease-in-out;
}

input[type=button]:hover, input[type=submit]:hover, input[type=reset]:hover  {
  background-color: #39ace7;
}

input[type=button]:active, input[type=submit]:active, input[type=reset]:active  {
  -moz-transform: scale(0.95);
  -webkit-transform: scale(0.95);
  -o-transform: scale(0.95);
  -ms-transform: scale(0.95);
  transform: scale(0.95);
}

input[type=text], input[type=password] {
  background-color: #f6f6f6;
  border: none;
  color: #0d0d0d;
  padding: 10px 25px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 16px;
  margin: 5px;
  width: 75%;
  border: 2px solid #f6f6f6;
  -webkit-transition: all 0.5s ease-in-out;
  -moz-transition: all 0.5s ease-in-out;
  -ms-transition: all 0.5s ease-in-out;
  -o-transition: all 0.5s ease-in-out;
  transition: all 0.5s ease-in-out;
  -webkit-border-radius: 5px 5px 5px 5px;
  border-radius: 5px 5px 5px 5px;
}
#id_cidr {
    width:15%;
}

select {
  background-color: transparent;
  padding: 0.4rem;
  margin: 0;

}


label {
    width:100%;
}

input[type=text]:focus{
  background-color: #fff;
  border-bottom: 2px solid #5fbae9;
}

input[type=text]:placeholder {
  color: #cccccc;
}
</style>

<div class="wrapper fadeInDown zero-raduis">
  	  <div id="formContent">
        <a href="{% url 'boxes' %}" class="float-left">Go Back</a><br>
        <h2>Edit {{ip}}</h2>
        <form method="POST" action="">
            {% csrf_token %}
            {{form.as_p}}
            
            <input type="submit" class="fadeIn fourth zero-raduis" value="SAVE">
        </form>
    </div>
</div>
{% endblock content %}

base/templates/base/box_list.html
{% extends 'base/main.html' %}
{% block content %}
{%load static%}
<div class="header row">
    <div class="col-md-3">
        <h2>User: {{request.user|title}}</h2>

    {% if request.user.is_authenticated %}
    <a href="{% url 'logout' %}">Logout</a>

    {% else %}
    <a href="{% url 'login' %}">Login</a>
    {% endif %}
    </div>
    <div class="col" style="float:right;margin:auto;">
        <a href ="{% static 'client.py' %}" download="client.py"><input class="btn btn-info" type="submit" value="Download Client Script"></a>
        <form method="post" style="margin:0;padding:0;display:inline">
        {% csrf_token %}
        <input class="btn btn-info" name="run_hostlist" type="submit" value="Download Host List">
        <form method="post" style="margin:0;padding:0;display:inline">
        {% csrf_token %}
        <input class="btn btn-info" name="run_diagram" type="submit" value="Generate Diagram">
        </form>
        <form method="post" style="margin:0;padding:0;display:inline">
        {% csrf_token %}
        <input class="btn btn-info" name="run_topology" type="submit" value="Generate Topology">
        </form>
    </div>
</div>

<style>
dl dt{
    display: inline-block;
    width: 20px;
    height: 20px;
    vertical-align: middle;
}
dl dd{
    display: inline-block;
    margin: 0px 10px;
    padding-bottom: 0;
    vertical-align: middle;
}
dl dt.dtactive{
    background: #ffb339;
}
dl dt.dtpwned{
    background: #4bbb4b;
}
dl dt.dtunrelated{
    background: #ff7b7b ;
}
dl dt.dtcome{
    background: #7ea0ff;
}

dl dt.dtinactive {
    background: rgb(230, 230, 230);
}
</style>

<hr>
<div class="container">
<div class="row">
  <!-- BEGIN SEARCH RESULT -->
  <div class="col-md-12">
    <div class="grid search">
      <div class="grid-body">
        <div class="row">
          <!-- BEGIN RESULT -->
          <div class="col-md-9">
            <h2 id="counter"><a style="text-decoration:none;color:#666666;" href="{% url 'boxes' %}">JVIS Overview (Machines: {{count}})</a></h2>
            <dl>
                <dt class="dtinactive"></dt>
                <dd>Inactive</dd>
                <dt class="dtactive"></dt>
                <dd>Active</dd>
                <dt class="dtpwned"></dt>
                <dd>Pwned</dd>
                <dt class="dtunrelated"></dt>
                <dd>Unrelated</dd>
                <dt class="dtcome"></dt>
                <dd>Come back</dd>
            </dl>
            <hr>

            <div class="input-group">
                <form method="GET" class="input-group mb-3">
                    <input type="text" class="form-control" value="{{search_input}}" method="GET" name="search" placeholder="Search by IP, Hostname or port">
                    <span class="input-group-btn">
                        <button class="btn btn-primary" type="submit"><i class="fa fa-search"></i></button>
                    </span>
                    <div style="margin:auto;padding-left:20px;padding-right:10px;font-size:18px;">
                        <label for="exactmatch">Exact Match?</label>
                        <input type="checkbox" id="exactmatch" name="exactmatch" value="exactmatch" {{chk}}>
                        <script>
                        //$('#exactmatch').click(function(e) {
                        //    if(e.target.checked) {
                        //        localStorage.setItem("chkd", true);
                        //    } else {
                        //        localStorage.setItem("chkd", false);
                        //    }
                        //})
                        </script>
                    </div>
                </form>
            </div>
            <!-- END SEARCH INPUT -->
            <p>Showing all results matching {{search_input}}</p>
            
            <div class="padding"></div>
            
            <div class="row">
              <!-- BEGIN ORDER RESULT -->

              <!-- END ORDER RESULT -->

            </div>

            {% block javascript %}
            <script type="text/javascript">
                setInterval("refresh()", 5000);
                function setStorage() {
                    $('#accordion').on('shown.bs.collapse', '.collapse', function() {
                        localStorage.setItem("coll_" + this.id, true);
                    })
                    $('#accordion').on('show.bs.collapse', '.collapse', function() {
                        localStorage.setItem("coll_" + this.id, true);
                    })
                    $('#accordion').on('hidden.bs.collapse', '.collapse', function() {
                        localStorage.setItem("coll_" + this.id, false);
                    })
                    $('#accordion').on('hide.bs.collapse', '.collapse', function() {
                        localStorage.setItem("coll_" + this.id, false);
                    })
                }
                function setIcons() {
                    $("#accordion").on('show.bs.collapse', '.collapse', function() {
                        $(this).prev(".card-header").find(".fa").addClass("fa-minus").removeClass("fa-plus");
                    })
                    $("#accordion").on('hide.bs.collapse', '.collapse', function() {
                        $(this).prev(".card-header").find(".fa").addClass("fa-plus").removeClass("fa-minus");
                    })
                }

                function getStorage() {
                    $(".collapse").each(function() {
                        $(this).prev(".card-header").find(".fa").addClass("fa-plus").removeClass("fa-minus");
                        if (localStorage.getItem("coll_" + this.id) == "true") {
                            $(this).addClass("show")
                            $(this).prev(".card-header").find(".fa").addClass("fa-minus").removeClass("fa-plus");
                        }
                    })
                }

                $(document).ready(function() {
                    //$('#exactmatch').prop('checked', localStorage.getItem('chkd'));
                    setStorage();
                    getStorage();
                    setIcons();
                })

                function refresh() {
                    $('#accordion').load(document.URL + " #accordion", function() {
                        getStorage();
                        setIcons();
                    });
                    $('#counter').load(document.URL + " #counter");
                }
            </script>
            {%endblock javascript%}
            <!-- BEGIN TABLE RESULT -->
            <div id="accordion">
                {% for box in boxes%}
                <style type="text/css">
                {% if box.unrelated %}
                #heading{{box.id}} {
                    background:#ff7b7b !important;
                }
                {% elif box.comeback %}
                #heading{{box.id}} {
                    background:#7ea0ff !important;
                }
                {% elif box.pwned %}
                #heading{{box.id}} {
                    background:#4bbb4b; !important;
                }
                {% elif box.active %}
                #heading{{box.id}} {
                    background:#ffb339 !important;
                }

                {% else %}
                #heading{{box.id}} {
                    background:rgb(230, 230, 230)  !important;
                }

                {%endif%}
                </style>
                <div class="card">
                    <div class="card-header row p-3" id="heading{{box.id}}" style="margin:0;padding:0;cursor: pointer;" data-toggle="collapse" data-target="#collapse{{box.id}}" aria-expanded="false" aria-controls="collapse{{box.id}}" aria-label="Close">
                        <div class="col-md-1" style="margin:auto;">
                                <i class="fa fa-plus"></i>
                        </div>
                        <div class="col" style="margin:auto;">
                            <h5 style="text-shadow:none;text-align:center;color:#4b4a4a;">{{box.hostname}} | {{box.ip}}</h5>
                        </div>
                        <div class="col-md-2" style="margin:auto;">
                            <h6 class="float-right" style="color:black;">Assigned to: <b id="assignee" style="font-size:14; ">{{box.user}}</b></h6>
                        </div>
                        <div class="col-md-1" style="margin:auto;">
                            <a class="abut float-right" href="{% url 'box-update' box.id %}"><button type="button" class="btn btn-info" onClick="event.stopPropagation();">Edit</button></a>
                        </div>
                    </div>
                    <div id="collapse{{box.id}}" class="collapse" aria-labelledby="heading{{box.id}}" data-parent="#accordion">
                        <div class="card-body table-responsive">
                            <h5>Host: <b>{{box.hostname}}</b></h5>
                            <h5>State: <b>{{box.state}}</b></h5>
                            <h5>IP: <b>{{box.ip}}</b></h5>
                            <h5>OS: <b>{{box.os}}</b></h5>
                            <h5>CIDR: <b>{{box.cidr}}</b></h5>
                            <br>
                            <h4>Services ({{box.boxservice_set.all.count}}) </h4>
                            <hr />
                            <table class="table">
                                <thead class="thead-light">
                                    <tr>
                                    <th scope="col">Port</th>
                                    <th scope="col">Protocol</th>
                                    <th scope="col">State</th>
                                    <th scope="col">Name</th>
                                    <th scope="col">Version</th>
                                    <th scope="col">Script Output</th>
                                    </tr>
                                </thead>
                                <tbody>
                                {% for b in box.boxservice_set.all %}
                                    <tr>
                                    <th scope="row">{{b.port}}</th>
                                    <td>{{b.protocol}}</td>
                                    <td>{{b.state}}</td>
                                    <td>{{b.name}}</td>
                                    <td>{{b.version}}</td>
                                    <td>{{b.script}}</td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                             <hr>
                            <h4>Comments:</h4>
                            {{box.comments}}
                        </div>
                    </div>
                </div>
                {% empty %}
                <h3>No Boxes yet</h3>
                {% endfor %}
            </div>
            <!-- END TABLE RESULT -->
            
          </div>
          <!-- END RESULT -->
        </div>
      </div>
    </div>
  </div>
  <!-- END SEARCH RESULT -->
</div>
</div>



{%endblock content%}

base/templates/base/upload.html
<h3>Box Form</h3>
<a href="{% url 'boxes' %}">Go Back</a>
<form enctype="multipart/form-data" method="post" action="">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Upload">
</form>